name: Publish Documentation

on:
  push:
    branches:
      - master
      - bld_ci_setuptools
  release:
    types:
      - published

jobs:
  deploy:
    # if: ${{ github.repository == 'ChristopherMayes/lume-impact' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/conda-setup
        with:
          python-version: ${{ matrix.python-version }}
          extras: "doc"

      #- name: Execute notebooks
      #  shell: bash -l {0}
      #  run: |
      #    pip install --no-dependencies . 
      #    scripts/execute_notebooks.bash 

      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build
          zip -r lume-impact-examples.zip docs/examples/
          mv lume-impact-examples.zip ./site/assets/.
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
